# Generated by Django 5.2.6 on 2025-09-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
