# Generated by Django 5.2.6 on 2025-09-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='작가')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
            ],
        ),
    ]
