# Generated by Django 5.2.6 on 2025-09-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='책')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='출시일')),
            ],
        ),
    ]
